Fix missing semicolon
```
fastpos.h:94:28: error: expected ';' before 'extern'
   94 | lzma_attr_visibility_hidden
      |                            ^
      |                            ;
   95 | extern const uint8_t lzma_fastpos[1 << FASTPOS_BITS];
      | ~~~~~~
```